DROP DATABASE IF EXISTS onibus;

CREATE DATABASE onibus CHARSET=UTF8 COLLATE utf8_general_ci;
USE onibus;

CREATE TABLE motorista(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cpf VARCHAR(20) NOT NULL,
  nome VARCHAR(50) NOT NULL
);
CREATE TABLE telefone(
  id_motorista INT NOT NULL AUTO_INCREMENT,
  telefone VARCHAR(20) NOT NULL,
  FOREIGN KEY (id_motorista) REFERENCES motorista(id) ON UPDATE CASCADE ON DELETE CASCADE 
);
CREATE TABLE linha(
  id VARCHAR(10) NOT NULL PRIMARY KEY,
  partida VARCHAR(20) NOT NULL,
  destino VARCHAR(20) NOT NULL,
  id_motorista INT NOT NULL AUTO_INCREMENT,
  FOREIGN KEY (id_motorista) REFERENCES motorista(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE linha_horario(
  id_linha VARCHAR(10) NOT NULL,
  horario_partida VARCHAR(10) NOT NULL,
  FOREIGN KEY (id_linha) REFERENCES linha(id) ON UPDATE CASCADE ON DELETE CASCADE
);