DROP DATABASE IF EXISTS clientes;

CREATE DATABASE clientes CHARSET=UTF8 COLLATE utf8_general_ci;
USE clientes;

CREATE TABLE cliente(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  nascimento DATE NOT NULL,
  sexo CHAR NOT NULL,
  peso FLOAT NOT NULL
);
CREATE TABLE telefone(
  id_cliente INT NOT NULL AUTO_INCREMENT,
  telefone VARCHAR(20) NOT NULL,
  FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON UPDATE CASCADE ON DELETE CASCADE
);